export const Colors = {
  primary: '#F59E0B',
  primaryLight: '#FEF3C7',
  primaryDark: '#D97706',
  background: '#FFFBF0',
  card: '#FFFFFF',
  cardBorder: '#E7E5E4',
  divider: '#F5F5F0',
  textPrimary: '#2D2D2D',
  textSecondary: '#78716C',
  textPlaceholder: '#A8A29E',
  success: '#22C55E',
  successLight: '#DCFCE7',
  successBorder: '#BBF7D0',
  error: '#EF4444',
  errorLight: '#FEE2E2',
  errorLightBg: '#FEF2F2',
  errorBorder: '#FCA5A5',
  upcoming: '#F5F5F0',
  purpleLight: '#EDE9FE',
  purpleIcon: '#7C3AED',
  tabInactive: '#A8A29E',
  tabBarBg: '#FFFFFF',
  tabBarBorder: '#E7E5E4',
} as const;
